# FB15k
sudo /home/ubuntu/anaconda3/envs/dgl/bin/python /home/ubuntu/project/dgl-ke/python/ke_test.py --model_name AttH --dataset FB15k --batch_size 1024 --neg_sample_size 256 --hidden_dim 64 --gamma 5 --lr 0.05 --max_step 24000 --log_interval 1000 --batch_size_eval 16  --test --gpu 0 --loss_genre Logsigmoid --num_proc 1 --mode fit -adv;
sudo /home/ubuntu/anaconda3/envs/dgl/bin/python /home/ubuntu/project/dgl-ke/python/ke_test.py --model_name AttH --dataset FB15k --batch_size 1024 --neg_sample_size 256 --hidden_dim 128 --gamma 5 --lr 0.05 --max_step 24000 --log_interval 1000 --batch_size_eval 16  --test --gpu 0 --loss_genre Logsigmoid --num_proc 1 --mode fit -adv  ;
sudo /home/ubuntu/anaconda3/envs/dgl/bin/python /home/ubuntu/project/dgl-ke/python/ke_test.py --model_name AttH --dataset FB15k --batch_size 1024 --neg_sample_size 256 --hidden_dim 200 --gamma 5 --lr 0.05 --max_step 24000 --log_interval 1000 --batch_size_eval 16  --test --gpu 0 --loss_genre Logsigmoid --num_proc 1 --mode fit -adv  ;
sudo /home/ubuntu/anaconda3/envs/dgl/bin/python /home/ubuntu/project/dgl-ke/python/ke_test.py --model_name AttH --dataset FB15k --batch_size 1024 --neg_sample_size 256 --hidden_dim 64 --gamma 5 --lr 0.1 --max_step 24000 --log_interval 1000 --batch_size_eval 16  --test --gpu 0 --loss_genre Logsigmoid --num_proc 1 --mode fit -adv  ;
sudo /home/ubuntu/anaconda3/envs/dgl/bin/python /home/ubuntu/project/dgl-ke/python/ke_test.py --model_name AttH --dataset FB15k --batch_size 1024 --neg_sample_size 256 --hidden_dim 128 --gamma 5 --lr 0.1 --max_step 24000 --log_interval 1000 --batch_size_eval 16  --test --gpu 0 --loss_genre Logsigmoid --num_proc 1 --mode fit -adv  ;
sudo /home/ubuntu/anaconda3/envs/dgl/bin/python /home/ubuntu/project/dgl-ke/python/ke_test.py --model_name AttH --dataset FB15k --batch_size 1024 --neg_sample_size 256 --hidden_dim 200 --gamma 5 --lr 0.1 --max_step 24000 --log_interval 1000 --batch_size_eval 16  --test --gpu 0 --loss_genre Logsigmoid --num_proc 1 --mode fit -adv  ;
sudo /home/ubuntu/anaconda3/envs/dgl/bin/python /home/ubuntu/project/dgl-ke/python/ke_test.py --model_name AttH --dataset FB15k --batch_size 1024 --neg_sample_size 256 --hidden_dim 64 --gamma 5 --lr 0.005 --max_step 24000 --log_interval 1000 --batch_size_eval 16  --test --gpu 0 --loss_genre Logsigmoid --num_proc 1 --mode fit -adv  ;
sudo /home/ubuntu/anaconda3/envs/dgl/bin/python /home/ubuntu/project/dgl-ke/python/ke_test.py --model_name AttH --dataset FB15k --batch_size 1024 --neg_sample_size 256 --hidden_dim 128 --gamma 5 --lr 0.005 --max_step 24000 --log_interval 1000 --batch_size_eval 16  --test --gpu 0 --loss_genre Logsigmoid --num_proc 1 --mode fit -adv  ;
sudo /home/ubuntu/anaconda3/envs/dgl/bin/python /home/ubuntu/project/dgl-ke/python/ke_test.py --model_name AttH --dataset FB15k --batch_size 1024 --neg_sample_size 256 --hidden_dim 200 --gamma 5 --lr 0.005 --max_step 24000 --log_interval 1000 --batch_size_eval 16  --test --gpu 0 --loss_genre Logsigmoid --num_proc 1 --mode fit -adv  ;

sudo /home/ubuntu/anaconda3/envs/dgl/bin/python /home/ubuntu/project/dgl-ke/python/ke_test.py --model_name AttH --dataset FB15k --batch_size 1024 --neg_sample_size 256 --hidden_dim 64 --gamma 5 --lr 0.05 --max_step 24000 --log_interval 1000 --batch_size_eval 16  --test --gpu 0 --loss_genre Logsigmoid --num_proc 1 --mode fit -adv  ;
sudo /home/ubuntu/anaconda3/envs/dgl/bin/python /home/ubuntu/project/dgl-ke/python/ke_test.py --model_name AttH --dataset FB15k --batch_size 1024 --neg_sample_size 256 --hidden_dim 128 --gamma 5 --lr 0.05 --max_step 24000 --log_interval 1000 --batch_size_eval 16  --test --gpu 0 --loss_genre Logsigmoid --num_proc 1 --mode fit -adv  ;
sudo /home/ubuntu/anaconda3/envs/dgl/bin/python /home/ubuntu/project/dgl-ke/python/ke_test.py --model_name AttH --dataset FB15k --batch_size 1024 --neg_sample_size 256 --hidden_dim 200 --gamma 5 --lr 0.05 --max_step 24000 --log_interval 1000 --batch_size_eval 16  --test --gpu 0 --loss_genre Logsigmoid --num_proc 1 --mode fit -adv  ;
sudo /home/ubuntu/anaconda3/envs/dgl/bin/python /home/ubuntu/project/dgl-ke/python/ke_test.py --model_name AttH --dataset FB15k --batch_size 1024 --neg_sample_size 256 --hidden_dim 64 --gamma 5 --lr 0.1 --max_step 24000 --log_interval 1000 --batch_size_eval 16  --test --gpu 0 --loss_genre Logsigmoid --num_proc 1 --mode fit -adv  ;
sudo /home/ubuntu/anaconda3/envs/dgl/bin/python /home/ubuntu/project/dgl-ke/python/ke_test.py --model_name AttH --dataset FB15k --batch_size 1024 --neg_sample_size 256 --hidden_dim 128 --gamma 5 --lr 0.1 --max_step 24000 --log_interval 1000 --batch_size_eval 16  --test --gpu 0 --loss_genre Logsigmoid --num_proc 1 --mode fit -adv  ;
sudo /home/ubuntu/anaconda3/envs/dgl/bin/python /home/ubuntu/project/dgl-ke/python/ke_test.py --model_name AttH --dataset FB15k --batch_size 1024 --neg_sample_size 256 --hidden_dim 200 --gamma 5 --lr 0.1 --max_step 24000 --log_interval 1000 --batch_size_eval 16  --test --gpu 0 --loss_genre Logsigmoid --num_proc 1 --mode fit -adv  ;
sudo /home/ubuntu/anaconda3/envs/dgl/bin/python /home/ubuntu/project/dgl-ke/python/ke_test.py --model_name AttH --dataset FB15k --batch_size 1024 --neg_sample_size 256 --hidden_dim 64 --gamma 5 --lr 0.005 --max_step 24000 --log_interval 1000 --batch_size_eval 16  --test --gpu 0 --loss_genre Logsigmoid --num_proc 1 --mode fit -adv  ;
sudo /home/ubuntu/anaconda3/envs/dgl/bin/python /home/ubuntu/project/dgl-ke/python/ke_test.py --model_name AttH --dataset FB15k --batch_size 1024 --neg_sample_size 256 --hidden_dim 128 --gamma 5 --lr 0.005 --max_step 24000 --log_interval 1000 --batch_size_eval 16  --test --gpu 0 --loss_genre Logsigmoid --num_proc 1 --mode fit -adv  ;
sudo /home/ubuntu/anaconda3/envs/dgl/bin/python /home/ubuntu/project/dgl-ke/python/ke_test.py --model_name AttH --dataset FB15k --batch_size 1024 --neg_sample_size 256 --hidden_dim 200 --gamma 5 --lr 0.005 --max_step 24000 --log_interval 1000 --batch_size_eval 16  --test --gpu 0 --loss_genre Logsigmoid --num_proc 1 --mode fit -adv  ;

sudo /home/ubuntu/anaconda3/envs/dgl/bin/python /home/ubuntu/project/dgl-ke/python/ke_test.py --model_name AttH --dataset FB15k --batch_size 1024 --neg_sample_size 256 --hidden_dim 64 --gamma 5 --lr 0.05 --max_step 24000 --log_interval 1000 --batch_size_eval 16  --test --gpu 0 --loss_genre Logsigmoid --num_proc 1 --mode fit -adv --regularization_coef 1e-07  ;
sudo /home/ubuntu/anaconda3/envs/dgl/bin/python /home/ubuntu/project/dgl-ke/python/ke_test.py --model_name AttH --dataset FB15k --batch_size 1024 --neg_sample_size 256 --hidden_dim 128 --gamma 5 --lr 0.05 --max_step 24000 --log_interval 1000 --batch_size_eval 16  --test --gpu 0 --loss_genre Logsigmoid --num_proc 1 --mode fit -adv --regularization_coef 1e-07  ;
sudo /home/ubuntu/anaconda3/envs/dgl/bin/python /home/ubuntu/project/dgl-ke/python/ke_test.py --model_name AttH --dataset FB15k --batch_size 1024 --neg_sample_size 256 --hidden_dim 200 --gamma 5 --lr 0.05 --max_step 24000 --log_interval 1000 --batch_size_eval 16  --test --gpu 0 --loss_genre Logsigmoid --num_proc 1 --mode fit -adv --regularization_coef 1e-07  ;
sudo /home/ubuntu/anaconda3/envs/dgl/bin/python /home/ubuntu/project/dgl-ke/python/ke_test.py --model_name AttH --dataset FB15k --batch_size 1024 --neg_sample_size 256 --hidden_dim 64 --gamma 5 --lr 0.1 --max_step 24000 --log_interval 1000 --batch_size_eval 16  --test --gpu 0 --loss_genre Logsigmoid --num_proc 1 --mode fit -adv --regularization_coef 1e-07  ;
sudo /home/ubuntu/anaconda3/envs/dgl/bin/python /home/ubuntu/project/dgl-ke/python/ke_test.py --model_name AttH --dataset FB15k --batch_size 1024 --neg_sample_size 256 --hidden_dim 128 --gamma 5 --lr 0.1 --max_step 24000 --log_interval 1000 --batch_size_eval 16  --test --gpu 0 --loss_genre Logsigmoid --num_proc 1 --mode fit -adv --regularization_coef 1e-07  ;
sudo /home/ubuntu/anaconda3/envs/dgl/bin/python /home/ubuntu/project/dgl-ke/python/ke_test.py --model_name AttH --dataset FB15k --batch_size 1024 --neg_sample_size 256 --hidden_dim 200 --gamma 5 --lr 0.1 --max_step 24000 --log_interval 1000 --batch_size_eval 16  --test --gpu 0 --loss_genre Logsigmoid --num_proc 1 --mode fit -adv --regularization_coef 1e-07  ;
sudo /home/ubuntu/anaconda3/envs/dgl/bin/python /home/ubuntu/project/dgl-ke/python/ke_test.py --model_name AttH --dataset FB15k --batch_size 1024 --neg_sample_size 256 --hidden_dim 64 --gamma 5 --lr 0.005 --max_step 24000 --log_interval 1000 --batch_size_eval 16  --test --gpu 0 --loss_genre Logsigmoid --num_proc 1 --mode fit -adv --regularization_coef 1e-07  ;
sudo /home/ubuntu/anaconda3/envs/dgl/bin/python /home/ubuntu/project/dgl-ke/python/ke_test.py --model_name AttH --dataset FB15k --batch_size 1024 --neg_sample_size 256 --hidden_dim 128 --gamma 5 --lr 0.005 --max_step 24000 --log_interval 1000 --batch_size_eval 16  --test --gpu 0 --loss_genre Logsigmoid --num_proc 1 --mode fit -adv --regularization_coef 1e-07  ;
sudo /home/ubuntu/anaconda3/envs/dgl/bin/python /home/ubuntu/project/dgl-ke/python/ke_test.py --model_name AttH --dataset FB15k --batch_size 1024 --neg_sample_size 256 --hidden_dim 200 --gamma 5 --lr 0.005 --max_step 24000 --log_interval 1000 --batch_size_eval 16  --test --gpu 0 --loss_genre Logsigmoid --num_proc 1 --mode fit -adv --regularization_coef 1e-07  ;

sudo /home/ubuntu/anaconda3/envs/dgl/bin/python /home/ubuntu/project/dgl-ke/python/ke_test.py --model_name AttH --dataset FB15k --batch_size 1024 --neg_sample_size 256 --hidden_dim 64 --gamma 5 --lr 0.05 --max_step 24000 --log_interval 1000 --batch_size_eval 16  --test --gpu 0 --loss_genre Logsigmoid --num_proc 1 --mode fit -adv --regularization_coef 1e-07  ;
sudo /home/ubuntu/anaconda3/envs/dgl/bin/python /home/ubuntu/project/dgl-ke/python/ke_test.py --model_name AttH --dataset FB15k --batch_size 1024 --neg_sample_size 256 --hidden_dim 128 --gamma 5 --lr 0.05 --max_step 24000 --log_interval 1000 --batch_size_eval 16  --test --gpu 0 --loss_genre Logsigmoid --num_proc 1 --mode fit -adv --regularization_coef 1e-07  ;
sudo /home/ubuntu/anaconda3/envs/dgl/bin/python /home/ubuntu/project/dgl-ke/python/ke_test.py --model_name AttH --dataset FB15k --batch_size 1024 --neg_sample_size 256 --hidden_dim 200 --gamma 5 --lr 0.05 --max_step 24000 --log_interval 1000 --batch_size_eval 16  --test --gpu 0 --loss_genre Logsigmoid --num_proc 1 --mode fit -adv --regularization_coef 1e-07  ;
sudo /home/ubuntu/anaconda3/envs/dgl/bin/python /home/ubuntu/project/dgl-ke/python/ke_test.py --model_name AttH --dataset FB15k --batch_size 1024 --neg_sample_size 256 --hidden_dim 64 --gamma 5 --lr 0.1 --max_step 24000 --log_interval 1000 --batch_size_eval 16  --test --gpu 0 --loss_genre Logsigmoid --num_proc 1 --mode fit -adv --regularization_coef 1e-07  ;
sudo /home/ubuntu/anaconda3/envs/dgl/bin/python /home/ubuntu/project/dgl-ke/python/ke_test.py --model_name AttH --dataset FB15k --batch_size 1024 --neg_sample_size 256 --hidden_dim 128 --gamma 5 --lr 0.1 --max_step 24000 --log_interval 1000 --batch_size_eval 16  --test --gpu 0 --loss_genre Logsigmoid --num_proc 1 --mode fit -adv --regularization_coef 1e-07  ;
sudo /home/ubuntu/anaconda3/envs/dgl/bin/python /home/ubuntu/project/dgl-ke/python/ke_test.py --model_name AttH --dataset FB15k --batch_size 1024 --neg_sample_size 256 --hidden_dim 200 --gamma 5 --lr 0.1 --max_step 24000 --log_interval 1000 --batch_size_eval 16  --test --gpu 0 --loss_genre Logsigmoid --num_proc 1 --mode fit -adv --regularization_coef 1e-07  ;
sudo /home/ubuntu/anaconda3/envs/dgl/bin/python /home/ubuntu/project/dgl-ke/python/ke_test.py --model_name AttH --dataset FB15k --batch_size 1024 --neg_sample_size 256 --hidden_dim 64 --gamma 5 --lr 0.005 --max_step 24000 --log_interval 1000 --batch_size_eval 16  --test --gpu 0 --loss_genre Logsigmoid --num_proc 1 --mode fit -adv --regularization_coef 1e-07  ;
sudo /home/ubuntu/anaconda3/envs/dgl/bin/python /home/ubuntu/project/dgl-ke/python/ke_test.py --model_name AttH --dataset FB15k --batch_size 1024 --neg_sample_size 256 --hidden_dim 128 --gamma 5 --lr 0.005 --max_step 24000 --log_interval 1000 --batch_size_eval 16  --test --gpu 0 --loss_genre Logsigmoid --num_proc 1 --mode fit -adv --regularization_coef 1e-07  ;
sudo /home/ubuntu/anaconda3/envs/dgl/bin/python /home/ubuntu/project/dgl-ke/python/ke_test.py --model_name AttH --dataset FB15k --batch_size 1024 --neg_sample_size 256 --hidden_dim 200 --gamma 5 --lr 0.005 --max_step 24000 --log_interval 1000 --batch_size_eval 16  --test --gpu 0 --loss_genre Logsigmoid --num_proc 1 --mode fit -adv --regularization_coef 1e-07  ;

sudo /home/ubuntu/anaconda3/envs/dgl/bin/python /home/ubuntu/project/dgl-ke/python/ke_test.py --model_name AttH --dataset FB15k --batch_size 1024 --neg_sample_size 256 --hidden_dim 64 --gamma 5 --lr 0.05 --max_step 24000 --log_interval 1000 --batch_size_eval 16  --test --gpu 0 --loss_genre Logsigmoid --num_proc 1 --mode fit -adv --regularization_coef 1e-08  ;
sudo /home/ubuntu/anaconda3/envs/dgl/bin/python /home/ubuntu/project/dgl-ke/python/ke_test.py --model_name AttH --dataset FB15k --batch_size 1024 --neg_sample_size 256 --hidden_dim 128 --gamma 5 --lr 0.05 --max_step 24000 --log_interval 1000 --batch_size_eval 16  --test --gpu 0 --loss_genre Logsigmoid --num_proc 1 --mode fit -adv --regularization_coef 1e-08  ;
sudo /home/ubuntu/anaconda3/envs/dgl/bin/python /home/ubuntu/project/dgl-ke/python/ke_test.py --model_name AttH --dataset FB15k --batch_size 1024 --neg_sample_size 256 --hidden_dim 200 --gamma 5 --lr 0.05 --max_step 24000 --log_interval 1000 --batch_size_eval 16  --test --gpu 0 --loss_genre Logsigmoid --num_proc 1 --mode fit -adv --regularization_coef 1e-08  ;
sudo /home/ubuntu/anaconda3/envs/dgl/bin/python /home/ubuntu/project/dgl-ke/python/ke_test.py --model_name AttH --dataset FB15k --batch_size 1024 --neg_sample_size 256 --hidden_dim 64 --gamma 5 --lr 0.1 --max_step 24000 --log_interval 1000 --batch_size_eval 16  --test --gpu 0 --loss_genre Logsigmoid --num_proc 1 --mode fit -adv --regularization_coef 1e-08  ;
sudo /home/ubuntu/anaconda3/envs/dgl/bin/python /home/ubuntu/project/dgl-ke/python/ke_test.py --model_name AttH --dataset FB15k --batch_size 1024 --neg_sample_size 256 --hidden_dim 128 --gamma 5 --lr 0.1 --max_step 24000 --log_interval 1000 --batch_size_eval 16  --test --gpu 0 --loss_genre Logsigmoid --num_proc 1 --mode fit -adv --regularization_coef 1e-08  ;
sudo /home/ubuntu/anaconda3/envs/dgl/bin/python /home/ubuntu/project/dgl-ke/python/ke_test.py --model_name AttH --dataset FB15k --batch_size 1024 --neg_sample_size 256 --hidden_dim 200 --gamma 5 --lr 0.1 --max_step 24000 --log_interval 1000 --batch_size_eval 16  --test --gpu 0 --loss_genre Logsigmoid --num_proc 1 --mode fit -adv --regularization_coef 1e-08  ;
sudo /home/ubuntu/anaconda3/envs/dgl/bin/python /home/ubuntu/project/dgl-ke/python/ke_test.py --model_name AttH --dataset FB15k --batch_size 1024 --neg_sample_size 256 --hidden_dim 64 --gamma 5 --lr 0.005 --max_step 24000 --log_interval 1000 --batch_size_eval 16  --test --gpu 0 --loss_genre Logsigmoid --num_proc 1 --mode fit -adv --regularization_coef 1e-08  ;
sudo /home/ubuntu/anaconda3/envs/dgl/bin/python /home/ubuntu/project/dgl-ke/python/ke_test.py --model_name AttH --dataset FB15k --batch_size 1024 --neg_sample_size 256 --hidden_dim 128 --gamma 5 --lr 0.005 --max_step 24000 --log_interval 1000 --batch_size_eval 16  --test --gpu 0 --loss_genre Logsigmoid --num_proc 1 --mode fit -adv --regularization_coef 1e-08  ;
sudo /home/ubuntu/anaconda3/envs/dgl/bin/python /home/ubuntu/project/dgl-ke/python/ke_test.py --model_name AttH --dataset FB15k --batch_size 1024 --neg_sample_size 256 --hidden_dim 200 --gamma 5 --lr 0.005 --max_step 24000 --log_interval 1000 --batch_size_eval 16  --test --gpu 0 --loss_genre Logsigmoid --num_proc 1 --mode fit -adv --regularization_coef 1e-08  ;

sudo /home/ubuntu/anaconda3/envs/dgl/bin/python /home/ubuntu/project/dgl-ke/python/ke_test.py --model_name AttH --dataset FB15k --batch_size 1024 --neg_sample_size 256 --hidden_dim 64 --gamma 5 --lr 0.05 --max_step 24000 --log_interval 1000 --batch_size_eval 16  --test --gpu 0 --loss_genre Logsigmoid --num_proc 1 --mode fit -adv --regularization_coef 1e-08  ;
sudo /home/ubuntu/anaconda3/envs/dgl/bin/python /home/ubuntu/project/dgl-ke/python/ke_test.py --model_name AttH --dataset FB15k --batch_size 1024 --neg_sample_size 256 --hidden_dim 128 --gamma 5 --lr 0.05 --max_step 24000 --log_interval 1000 --batch_size_eval 16  --test --gpu 0 --loss_genre Logsigmoid --num_proc 1 --mode fit -adv --regularization_coef 1e-08  ;
sudo /home/ubuntu/anaconda3/envs/dgl/bin/python /home/ubuntu/project/dgl-ke/python/ke_test.py --model_name AttH --dataset FB15k --batch_size 1024 --neg_sample_size 256 --hidden_dim 200 --gamma 5 --lr 0.05 --max_step 24000 --log_interval 1000 --batch_size_eval 16  --test --gpu 0 --loss_genre Logsigmoid --num_proc 1 --mode fit -adv --regularization_coef 1e-08  ;
sudo /home/ubuntu/anaconda3/envs/dgl/bin/python /home/ubuntu/project/dgl-ke/python/ke_test.py --model_name AttH --dataset FB15k --batch_size 1024 --neg_sample_size 256 --hidden_dim 64 --gamma 5 --lr 0.1 --max_step 24000 --log_interval 1000 --batch_size_eval 16  --test --gpu 0 --loss_genre Logsigmoid --num_proc 1 --mode fit -adv --regularization_coef 1e-08  ;
sudo /home/ubuntu/anaconda3/envs/dgl/bin/python /home/ubuntu/project/dgl-ke/python/ke_test.py --model_name AttH --dataset FB15k --batch_size 1024 --neg_sample_size 256 --hidden_dim 128 --gamma 5 --lr 0.1 --max_step 24000 --log_interval 1000 --batch_size_eval 16  --test --gpu 0 --loss_genre Logsigmoid --num_proc 1 --mode fit -adv --regularization_coef 1e-08  ;
sudo /home/ubuntu/anaconda3/envs/dgl/bin/python /home/ubuntu/project/dgl-ke/python/ke_test.py --model_name AttH --dataset FB15k --batch_size 1024 --neg_sample_size 256 --hidden_dim 200 --gamma 5 --lr 0.1 --max_step 24000 --log_interval 1000 --batch_size_eval 16  --test --gpu 0 --loss_genre Logsigmoid --num_proc 1 --mode fit -adv --regularization_coef 1e-08  ;
sudo /home/ubuntu/anaconda3/envs/dgl/bin/python /home/ubuntu/project/dgl-ke/python/ke_test.py --model_name AttH --dataset FB15k --batch_size 1024 --neg_sample_size 256 --hidden_dim 64 --gamma 5 --lr 0.005 --max_step 24000 --log_interval 1000 --batch_size_eval 16  --test --gpu 0 --loss_genre Logsigmoid --num_proc 1 --mode fit -adv --regularization_coef 1e-08  ;
sudo /home/ubuntu/anaconda3/envs/dgl/bin/python /home/ubuntu/project/dgl-ke/python/ke_test.py --model_name AttH --dataset FB15k --batch_size 1024 --neg_sample_size 256 --hidden_dim 128 --gamma 5 --lr 0.005 --max_step 24000 --log_interval 1000 --batch_size_eval 16  --test --gpu 0 --loss_genre Logsigmoid --num_proc 1 --mode fit -adv --regularization_coef 1e-08  ;
sudo /home/ubuntu/anaconda3/envs/dgl/bin/python /home/ubuntu/project/dgl-ke/python/ke_test.py --model_name AttH --dataset FB15k --batch_size 1024 --neg_sample_size 256 --hidden_dim 200 --gamma 5 --lr 0.005 --max_step 24000 --log_interval 1000 --batch_size_eval 16  --test --gpu 0 --loss_genre Logsigmoid --num_proc 1 --mode fit -adv --regularization_coef 1e-08  ;

sudo /home/ubuntu/anaconda3/envs/dgl/bin/python /home/ubuntu/project/dgl-ke/python/ke_test.py --model_name AttH --dataset FB15k --batch_size 1024 --neg_sample_size 256 --hidden_dim 64 --gamma 5 --lr 0.05 --max_step 24000 --log_interval 1000 --batch_size_eval 16  --test --gpu 0 --loss_genre Logsigmoid --num_proc 1 --mode fit -adv --regularization_coef 1e-09  ;
sudo /home/ubuntu/anaconda3/envs/dgl/bin/python /home/ubuntu/project/dgl-ke/python/ke_test.py --model_name AttH --dataset FB15k --batch_size 1024 --neg_sample_size 256 --hidden_dim 128 --gamma 5 --lr 0.05 --max_step 24000 --log_interval 1000 --batch_size_eval 16  --test --gpu 0 --loss_genre Logsigmoid --num_proc 1 --mode fit -adv --regularization_coef 1e-09  ;
sudo /home/ubuntu/anaconda3/envs/dgl/bin/python /home/ubuntu/project/dgl-ke/python/ke_test.py --model_name AttH --dataset FB15k --batch_size 1024 --neg_sample_size 256 --hidden_dim 200 --gamma 5 --lr 0.05 --max_step 24000 --log_interval 1000 --batch_size_eval 16  --test --gpu 0 --loss_genre Logsigmoid --num_proc 1 --mode fit -adv --regularization_coef 1e-09  ;
sudo /home/ubuntu/anaconda3/envs/dgl/bin/python /home/ubuntu/project/dgl-ke/python/ke_test.py --model_name AttH --dataset FB15k --batch_size 1024 --neg_sample_size 256 --hidden_dim 64 --gamma 5 --lr 0.1 --max_step 24000 --log_interval 1000 --batch_size_eval 16  --test --gpu 0 --loss_genre Logsigmoid --num_proc 1 --mode fit -adv --regularization_coef 1e-09  ;
sudo /home/ubuntu/anaconda3/envs/dgl/bin/python /home/ubuntu/project/dgl-ke/python/ke_test.py --model_name AttH --dataset FB15k --batch_size 1024 --neg_sample_size 256 --hidden_dim 128 --gamma 5 --lr 0.1 --max_step 24000 --log_interval 1000 --batch_size_eval 16  --test --gpu 0 --loss_genre Logsigmoid --num_proc 1 --mode fit -adv --regularization_coef 1e-09  ;
sudo /home/ubuntu/anaconda3/envs/dgl/bin/python /home/ubuntu/project/dgl-ke/python/ke_test.py --model_name AttH --dataset FB15k --batch_size 1024 --neg_sample_size 256 --hidden_dim 200 --gamma 5 --lr 0.1 --max_step 24000 --log_interval 1000 --batch_size_eval 16  --test --gpu 0 --loss_genre Logsigmoid --num_proc 1 --mode fit -adv --regularization_coef 1e-09  ;
sudo /home/ubuntu/anaconda3/envs/dgl/bin/python /home/ubuntu/project/dgl-ke/python/ke_test.py --model_name AttH --dataset FB15k --batch_size 1024 --neg_sample_size 256 --hidden_dim 64 --gamma 5 --lr 0.005 --max_step 24000 --log_interval 1000 --batch_size_eval 16  --test --gpu 0 --loss_genre Logsigmoid --num_proc 1 --mode fit -adv --regularization_coef 1e-09  ;
sudo /home/ubuntu/anaconda3/envs/dgl/bin/python /home/ubuntu/project/dgl-ke/python/ke_test.py --model_name AttH --dataset FB15k --batch_size 1024 --neg_sample_size 256 --hidden_dim 128 --gamma 5 --lr 0.005 --max_step 24000 --log_interval 1000 --batch_size_eval 16  --test --gpu 0 --loss_genre Logsigmoid --num_proc 1 --mode fit -adv --regularization_coef 1e-09  ;
sudo /home/ubuntu/anaconda3/envs/dgl/bin/python /home/ubuntu/project/dgl-ke/python/ke_test.py --model_name AttH --dataset FB15k --batch_size 1024 --neg_sample_size 256 --hidden_dim 200 --gamma 5 --lr 0.005 --max_step 24000 --log_interval 1000 --batch_size_eval 16  --test --gpu 0 --loss_genre Logsigmoid --num_proc 1 --mode fit -adv --regularization_coef 1e-09  ;

sudo /home/ubuntu/anaconda3/envs/dgl/bin/python /home/ubuntu/project/dgl-ke/python/ke_test.py --model_name AttH --dataset FB15k --batch_size 1024 --neg_sample_size 256 --hidden_dim 64 --gamma 5 --lr 0.05 --max_step 24000 --log_interval 1000 --batch_size_eval 16  --test --gpu 0 --loss_genre Logsigmoid --num_proc 1 --mode fit -adv --regularization_coef 1e-09  ;
sudo /home/ubuntu/anaconda3/envs/dgl/bin/python /home/ubuntu/project/dgl-ke/python/ke_test.py --model_name AttH --dataset FB15k --batch_size 1024 --neg_sample_size 256 --hidden_dim 128 --gamma 5 --lr 0.05 --max_step 24000 --log_interval 1000 --batch_size_eval 16  --test --gpu 0 --loss_genre Logsigmoid --num_proc 1 --mode fit -adv --regularization_coef 1e-09  ;
sudo /home/ubuntu/anaconda3/envs/dgl/bin/python /home/ubuntu/project/dgl-ke/python/ke_test.py --model_name AttH --dataset FB15k --batch_size 1024 --neg_sample_size 256 --hidden_dim 200 --gamma 5 --lr 0.05 --max_step 24000 --log_interval 1000 --batch_size_eval 16  --test --gpu 0 --loss_genre Logsigmoid --num_proc 1 --mode fit -adv --regularization_coef 1e-09  ;
sudo /home/ubuntu/anaconda3/envs/dgl/bin/python /home/ubuntu/project/dgl-ke/python/ke_test.py --model_name AttH --dataset FB15k --batch_size 1024 --neg_sample_size 256 --hidden_dim 64 --gamma 5 --lr 0.1 --max_step 24000 --log_interval 1000 --batch_size_eval 16  --test --gpu 0 --loss_genre Logsigmoid --num_proc 1 --mode fit -adv --regularization_coef 1e-09  ;
sudo /home/ubuntu/anaconda3/envs/dgl/bin/python /home/ubuntu/project/dgl-ke/python/ke_test.py --model_name AttH --dataset FB15k --batch_size 1024 --neg_sample_size 256 --hidden_dim 128 --gamma 5 --lr 0.1 --max_step 24000 --log_interval 1000 --batch_size_eval 16  --test --gpu 0 --loss_genre Logsigmoid --num_proc 1 --mode fit -adv --regularization_coef 1e-09  ;
sudo /home/ubuntu/anaconda3/envs/dgl/bin/python /home/ubuntu/project/dgl-ke/python/ke_test.py --model_name AttH --dataset FB15k --batch_size 1024 --neg_sample_size 256 --hidden_dim 200 --gamma 5 --lr 0.1 --max_step 24000 --log_interval 1000 --batch_size_eval 16  --test --gpu 0 --loss_genre Logsigmoid --num_proc 1 --mode fit -adv --regularization_coef 1e-09  ;
sudo /home/ubuntu/anaconda3/envs/dgl/bin/python /home/ubuntu/project/dgl-ke/python/ke_test.py --model_name AttH --dataset FB15k --batch_size 1024 --neg_sample_size 256 --hidden_dim 64 --gamma 5 --lr 0.005 --max_step 24000 --log_interval 1000 --batch_size_eval 16  --test --gpu 0 --loss_genre Logsigmoid --num_proc 1 --mode fit -adv --regularization_coef 1e-09  ;
sudo /home/ubuntu/anaconda3/envs/dgl/bin/python /home/ubuntu/project/dgl-ke/python/ke_test.py --model_name AttH --dataset FB15k --batch_size 1024 --neg_sample_size 256 --hidden_dim 128 --gamma 5 --lr 0.005 --max_step 24000 --log_interval 1000 --batch_size_eval 16  --test --gpu 0 --loss_genre Logsigmoid --num_proc 1 --mode fit -adv --regularization_coef 1e-09  ;
sudo /home/ubuntu/anaconda3/envs/dgl/bin/python /home/ubuntu/project/dgl-ke/python/ke_test.py --model_name AttH --dataset FB15k --batch_size 1024 --neg_sample_size 256 --hidden_dim 200 --gamma 5 --lr 0.005 --max_step 24000 --log_interval 1000 --batch_size_eval 16  --test --gpu 0 --loss_genre Logsigmoid --num_proc 1 --mode fit -adv --regularization_coef 1e-09  ;

# for test
# sudo /home/ubuntu/anaconda3/envs/dgl/bin/python /home/ubuntu/project/dgl-ke/python/ke_test.py --model_name AttH --dataset FB15k --batch_size 1024 --neg_sample_size 256 --hidden_dim 64 --gamma 5 --lr 0.1 --max_step 24000 --log_interval 1000 --batch_size_eval 16  --test --gpu 0 --loss_genre Logsigmoid --num_proc 1 --mode fit -adv --regularization_coef 1e-09  ;
sudo /home/ubuntu/anaconda3/envs/dgl/bin/python /home/ubuntu/project/dgl-ke/python/ke_test.py --model_name TransE --dataset FB15k --batch_size 1000 --log_interval 1000 --neg_sample_size 200 --regularization_coef 1e-07 --hidden_dim 400 --gamma 16.0 --lr 0.01 --batch_size_eval 16 --test -adv --max_step 5 --mix_cpu_gpu  --gpu 0 1 2 3 4 5 6 7 --async_update --rel_part --force_sync_interval 1000 --num_proc 8